### ISSUE TITLE
ImportError: No module named pykdl_utils.kdl_kinematics

### ISSUE THREAD

**Issue by YantianZha** [kairproject/kair_algorithms_draft#91]
Dear All:

After running the command "rosrun kair_algorithms run_open_manipulator_reacher_v0.py --algo ddpgfd --off-render --log", I got the error:

Traceback (most recent call last):
  File "/home/local/ha3/mi_ws/src/kair_algorithms_draft/scripts/run_open_manipulator_reacher_v0.py", line 16, in <module>
    from envs.open_manipulator.open_manipulator_reacher_env import OpenManipulatorReacherEnv
  File "/home/local/ha3/mi_ws/src/kair_algorithms_draft/scripts/envs/__init__.py", line 1, in <module>
    from .open_manipulator import OpenManipulatorReacherEnv
  File "/home/local/ha3/mi_ws/src/kair_algorithms_draft/scripts/envs/open_manipulator/__init__.py", line 1, in <module>
    from .open_manipulator_reacher_env import OpenManipulatorReacherEnv
  File "/home/local/ha3/mi_ws/src/kair_algorithms_draft/scripts/envs/open_manipulator/open_manipulator_reacher_env.py", line 7, in <module>
    from ros_interface import (
  File "/home/local/ha3/mi_ws/src/kair_algorithms_draft/scripts/envs/open_manipulator/ros_interface.py", line 16, in <module>
    from pykdl_utils.kdl_kinematics import KDLKinematics
ImportError: No module named pykdl_utils.kdl_kinematics

Thanks for helping!

**Comment by YantianZha** [comment]
solved.
